= Everything wrong with Scrum



== What Scrum gets right

////

* Building regular customer feedback into the process (sprint review).

////

== What Scrum misses

=== Continuous refactoring

////

Scrum tends to be product-driven. For example, continuous refactoring is not
rewarded, because it doesn't immediately deliver value to the customer.
Instead, technical concerns such as refactoring and maintenance need to compete
with feature development for time and resources.

////

=== Built-in quality

////

People have this perception that agile is all about cutting corners to get
things done quickly - but this was never the intention of the authors of the
agile manifesto. The intention was to deliver high-quality software at a
_sustainable pace_ over the long term, not as quickly as possible in the short
term. This requires investing in the _quality_ of the product as much as the
quantity of its features.

Scrum doesn't have anything to say about built-in quality. It's all about
delivering features as quickly as possible. But if we don't have built-in
quality, then we will end up with a system that is difficult to maintain and
evolve.

This is a false economy, because it will slow us down in the long run.

Lean Engineering and Extreme Programming have a lot to say about built-in
quality, but these practices are not part of Scrum.

////

=== High-performing tams

////

Scrum has nothing to say about high-performing teams, which is all about
developing good habits that help the teams to work together effectively and
to achieve long-term goals.

Scrum's incentive structures are short-term.

And developers, like everyone, are very good at following incentive structures.
And if the incentive structure is to deliver features as quickly as possible,
then that's what we will do.

Communication is difficult, problem solving is difficult - these things are
seen as overheads and distractions from churning out code. But these are the
things that make high-performing teams over the long-term, and increase the
chances of successful software delivery.

Perhaps we've reinforced the stereotype that developers are introverted and
like to work alone on their own coding challenges, wearing hoodies and
headphones. But this is not the reality of software development in the
commercial world. Software _engineering_ is fundamentally a social activity.

So forming high-performing teams is all about team work, which is all about the
dynamics of the team and the soft skills of individuals within the team.

Scrum has nothing to say about this. Scrum is only a process model, and way
of organizing work into units of time. And many of the ideas in Scrum are
good ideas in this regard. But its not enough. This is not the essence of
software development.

////

=== Waterfall process

////

Big design up front
UAT

We do need some waterfall-esque processes from time-to-time.

If we did everything in thin vertical slices, we could end up with a pretty
messy system. It can make sense to do some big-design up front in vertical slices,
for example designing your data model and subdomains. This work should not be
iterative, because it _is_ difficult/expensive to change later on.

////s
